import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Jesse",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased bg-[#121212]`}>{children}</body>
    </html>
  );
}
